"""Write portable lab config snippets (JSON + shell) for conn.log streaming."""
from __future__ import annotations

import json
import time
from pathlib import Path
from typing import Any


def repo_root_from_any_path(anchor: Path) -> Path:
    """Resolve project root given a path (file or directory) — walks anchor then cwd."""
    anchor = anchor.resolve()
    for base in (anchor, *anchor.parents, Path.cwd().resolve(), *Path.cwd().resolve().parents):
        if (base / "pyproject.toml").is_file():
            return base
    raise ValueError(
        "Could not locate Hawk-Eye repo root (no pyproject.toml). "
        "Run commands from the repository tree, or pass repo_root= to write_stream_lab_artifacts."
    ).parent


def write_stream_lab_artifacts(
    *,
    conn_log_path: Path,
    scenario: str,
    line_count: int,
    repo_root: Path | None = None,
    config_dir: Path | None = None,
) -> dict[str, str]:
    """
    Write ``stream_lab.generated.json`` and ``hawk_eye_stream_env.sh`` under ``data/lab/``.
    Returns paths written.
    """
    conn_log_path = conn_log_path.resolve()
    root = repo_root or repo_root_from_any_path(conn_log_path)
    lab_dir = config_dir or (root / "data" / "lab")
    lab_dir.mkdir(parents=True, exist_ok=True)

    abs_conn = str(conn_log_path)
    try:
        conn_rel = str(conn_log_path.resolve().relative_to(root.resolve()))
    except ValueError:
        conn_rel = None
    payload: dict[str, Any] = {
        "schema": "hawk_eye.stream_lab.v1",
        "generated_at_unix": int(time.time()),
        "repo_root": str(root.resolve()),
        "conn_log_path": abs_conn,
        "conn_log_relative": conn_rel,
        "scenario": scenario,
        "line_count": line_count,
        "detection_settings_patch": {
            "conn_log_path": abs_conn,
            "active_dual_mode": "stream",
        },
        "env_exports": {
            "HAWK_EYE_DEFAULT_CONN_LOG": abs_conn,
        },
    }

    json_path = lab_dir / "stream_lab.generated.json"
    json_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")

    env_path = lab_dir / "hawk_eye_stream_env.sh"
    env_path.write_text(
        "# Generated by Hawk-Eye lab tooling — source before starting uvicorn:\n"
        f"#   source {env_path.resolve()}\n"
        f'export HAWK_EYE_DEFAULT_CONN_LOG="{abs_conn}"\n',
        encoding="utf-8",
    )

    # Optional: mirror under config/ for editors that only look at config/
    cfg_mirror = root / "config" / "generated_stream_lab.json"
    try:
        cfg_mirror.parent.mkdir(parents=True, exist_ok=True)
        cfg_mirror.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    except OSError:
        pass

    return {"json": str(json_path.resolve()), "env_sh": str(env_path.resolve()), "config_mirror": str(cfg_mirror.resolve())}


def write_stream_job_config_artifact(
    *,
    job_id: int,
    payload: dict[str, Any],
    summary: dict[str, Any],
    stream_sessions_dir: Path,
) -> Path | None:
    """Write ``job_<id>_stream_config.generated.json`` next to stream outputs."""
    out = {
        "schema": "hawk_eye.stream_job.v1",
        "job_id": job_id,
        "generated_at_unix": int(time.time()),
        "conn_log_path": payload.get("conn_log_path"),
        "binary_dir": payload.get("binary_dir"),
        "supervised_dir": payload.get("supervised_dir"),
        "anomaly_dir": payload.get("anomaly_dir"),
        "duration_seconds": payload.get("duration_seconds"),
        "poll_seconds": payload.get("poll_seconds"),
        "fusion": payload.get("fusion"),
        "summary": summary,
    }
    p = stream_sessions_dir / f"job_{job_id}_stream_config.generated.json"
    try:
        p.write_text(json.dumps(out, indent=2, default=str), encoding="utf-8")
        return p
    except OSError:
        return None
